version: '3.8'
services:
  app:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis
  db:
    image: postgres
    environment:
      POSTGRES_DB: rpglms
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
  redis:
    image: redis